export const posts=[
    {
        id:1,
        title:'The true measure of a man aint based on how he behaves in moments of joy and conveniences but how he stands during times of tribulations and controversies.',
        body:"According to the post shown on Kenya's finest broadcast, Lynnie in her statement hopes to reach thousands of people, young and old....",
        createAt:"2024-Feb-19 |11:00 Am Pst ",
        author:'Mohren',
        img:'/images/post.jpg',
    },
    {
        id:2,
        title:'The true measure of a man aint based on how he behaves in moments of joy and conveniences but how he stands during times of tribulations and controversies',
        body:"According to the post shown on Kenya's finest broadcast, Lynnie in her statement hopes to reach thousands of people, young and old....",
        createAt:"2024-Feb-19 |11:00 Am Pst ",
        author:'Gael',
        img:'/images/post.jpg',
    },
    {
        id:3,
        title:'The true measure of a man aint based on how he behaves in moments of joy and conveniences but how he stands during times of tribulations and controversies',
        body:"According to the post shown on Kenya's finest broadcast, Lynnie in her statement hopes to reach thousands of people, young and old....",
        createAt:"2024-Feb-19 |11:00 Am Pst ",
        author:'Gael',
        img:'/images/post.jpg',
    },
    {
        id:4,
        title:'The true measure of a man aint based on how he behaves in moments of joy and conveniences but how he stands during times of tribulations and controversies',
        body:"According to the post shown on Kenya's finest broadcast, Lynnie in her statement hopes to reach thousands of people, young and old....",
        createAt:"2024-Feb-19 |11:00 Am Pst ",
        author:'Gael',
        img:'/images/post.jpg',
    },
    {
        id:5,
        title:'The true measure of a man aint based on how he behaves in moments of joy and conveniences but how he stands during times of tribulations and controversies',
        body:"According to the post shown on Kenya's finest broadcast, Lynnie in her statement hopes to reach thousands of people, young and old....",
        createAt:"2024-Feb-19 |11:00 Am Pst ",
        author:'Gael',
        img:'/images/post.jpg',
    },
    {
        id:6,
        title:'The true measure of a man aint based on how he behaves in moments of joy and conveniences but how he stands during times of tribulations and controversies',
        body:"According to the post shown on Kenya's finest broadcast, Lynnie in her statement hopes to reach thousands of people, young and old....",
        createAt:"2024-Feb-19 |11:00 Am Pst ",
        author:'Gael',
        img:'/images/post.jpg',
    },
]