export const navigations =[
    {
        _id:1,
        path:"/",
        title:"Home",
    },
    {
        _id:2,
        path:"/about",
        title:"About",
    },
    {
        _id:3,
        path:"/blog",
        title:"Blog",
    },
    {
        _id:4,
        path:"/contact",
        title:"Contact",
    },
];